### ISSUE TITLE
Final review of I-D before submission (of version 9)

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#17]
By Weds 10th Feb

**Comment by dperdices** [comment]
I leave here the review. Most of the things are typos, inconsistencies and minor issues. As you see, it is divided in the same sections of the document so that it is easier to find the issues.

-----------------------------------------------------
## 1 Introduction
* ITU recommendations should be cite in a consistent way, i.e. instead of `G.694.1 [G.694.1] and G.872 [G.872]`, it should be `[G.694.1] and [G.872]`, the same way we cite RFCs or drafts.

* Typo `flexi-grid elements..`

## 3 Tree diagram

### 3.1 Prefixes in Data Node Names

* Should caption of the table be `Table 1:...` instead of `Figure 1:...`?

## 4 Example of use

* We should only keep the second version of the figure instead of both of them. 

* Reference in text should be `Figure 2` in this version, but as I pointed out in 3.1, maybe Figure 1 should be Table and this closes this issue.

## 6 Yang code 

* In contact leaf, Dan's email is not the same of section Authors' Addresses. (Not an issue but a piece of information for Dan in case he didn't notice).

* I think that should change the reference and description and use `RFC YYYY` instead of `RFC XXXX`. We have in section 3.1 this note 

```
RFC Editor Note: Please replace XXXX with the RFC numbers assigned to
draft-ietf-ccamp-layer0-types.  Please replace YYYY with the RFC
number assigned to this document.  Please remove this note.
```

and in the yang code this note

```
This version of this YANG module is part of RFC XXXX; see
the RFC itself for full legal notices.";

revision 2020-10-21 {
description
    "Initial Version";
reference
    "RFC XXXX: A YANG Data Model for Flexi-Grid Optical Networks";
// RFC Ed.: replace XXXX with actual RFC number, update date
// information and remove this note
}
```

It's not a big issue but something kind to the RFC Editors so that they can replace XXXX with RFC number for layer0-types and YYYY with our document's number :)

* Only validation warning is the one I pointed out in last meeting (solved in layer-0-types)

## 7 Security considerations

* `Secure Shell (SSH)` is used there three times. Should we just expand the first time? Maybe keep the ones that are titles of RFCs?  Also, should we expand TLS or is already well-known?

## 9 Contributors

* Daniel Michaud's corporative email should be `daniel.michaud@estudiante.uam.es` but it is probably already disabled. Jorge should confirm this.

* Maybe, for consistency, we should ask Victor and Oscar to have also their second surname as Jorge and I do. Or remove our second surname. It's not such a big deal in any case and should be left to each one's discretion.

* Italo's affiliation (Huawei) is not the same as Haomian's (Huawei Technologies). (Maybe they are different companies and I am messing this up, my apologies in advance in that case :) )

## 11 References

### 11.1 Normative references

* `Madrid, U.` should be `Lopez de Vergara, J. E.`

* `Lopezalvarez, V` should be `Lopez, V.` (or `Lopez-Alvarez, V.`)

* `Dios, O.` should be `Gonzalez de Dios, O.`

### 11.2 Informative references

* `ITUT` should be `ITU-T`
-------------------------------------

**Comment by italobusi** [comment]
Please find my review comments in embedded word comments: 
[draft-ietf-ccamp-flexigrid-yang-09-ib@2021-02-10.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/5959589/draft-ietf-ccamp-flexigrid-yang-09-ib%402021-02-10.docx)

Proposed text changes, marked with revision bars, are also provided.

**Comment by jorgelopezdevergara** [comment]
Given that Daniel Perdices is now working at Universidad Autónoma de Madrid, maybe we can switch these affiliations (as I am also at Naudit), to keep this information updated.
Daniel Perdices and I need to add acknowledgements to a national project (probably, instead of Trafica project that is currently there), and to a research scholar for Daniel Perdices. The new acks would be the funding by the Spanish State Research Agency under the project AgileMon (AEI PID2019-104451RB-C21) and by the Spanish Ministry of Science, Innovation and Universities under the program for the training of university lecturers (Grant number: FPU19/05678).
With respect to Daniel Michaud e-mail, I have his personal e-mail. I'm not sure if he needs to be contacted by e-mail, as we worked on this with me at the beginning of the draft. If the e-mail is needed, we can put his UAM e-mail (daniel.michaud@estudiante.uam.es).

**Comment by sergiobelotti** [comment]
I have some comments about the version 9 that I collected in this attached word version.
[draft-ietf-ccamp-flexigrid-yang-09-comment-SB.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/5965004/draft-ietf-ccamp-flexigrid-yang-09-comment-SB.docx)

**Comment by danielkinguk** [comment]
Add some short text stating that media channel resource model is discussion in draft-ietf-ccamp-flex-media-foo and not in scope of this document.
