### ISSUE TITLE
Tree Structure 

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#30]
Having 17 pages of a tree diagram without any explanation for the different sections of the tree diagram is hardly helpful. On the other hand an abridged version of the tree diagram explaining the different sections would be more helpful normative text. Suggest that --tree-depth and --tree-path options be used in pyang to reduce the size of the tree and to break it up into smaller
pieces that can then be explained. The full tree diagram can be added as non-normative text in the Appendix.

This is a valid comment, having looked at other YANG models I found https://datatracker.ietf.org/doc/html/draft-ietf-opsawg-l3sm-l3nm-07#section-7 as a good example.

**Comment by italobusi** [comment]
Please find some proposed text for clause 5 (similar to the text we have provided for OTN topology) to address this issue

[draft-ietf-ccamp-flexigrid-yang-09-ib@2021-04-26.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/6390242/draft-ietf-ccamp-flexigrid-yang-09-ib%402021-04-26.docx)

Please note that this document contains also some review comments to other sections of the draft (for further discussion)

**Comment by dperdices** [comment]
Thank you, Italo! In my opinion, this new section 5 is really explanatory and makes the model easier to understand so readers will surely appreciate it.

I leave here some minor issues to check before merging. (English-related things should be double-checked by @danielkinguk, just in case I report things that are in fact correct, my apologies in advance).
- "Therefore the YANG" => "Therefore, the YANG"
- "an Flexi-Grid" => "a flexi-grid"
- In the rest of the document, we use flexi-grid (with this capitalization, instead of Flexi-Grid)
- Section 3.2 should not be 3.2 but 5.X. In general, when merging this, we should revise the section numbering.
- "in the topology as follow." => "in the topology as follows:"
- "Therefore the model does not define" => "Therefore, the model does not define"

**Comment by danielkinguk** [comment]
Dan to integrate into XML version v10.
